
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu May 29 2025 09:26:40 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Menu extends ContentItem {
    public whitelogo!: Elements.AssetsElement;
    public menuLogo!: Elements.AssetsElement;
    public linkedinurl!: Elements.TextElement;
    public facebookurl!: Elements.TextElement;
    public twitterurl!: Elements.TextElement;
    public instagramurl!: Elements.TextElement;
    public youtubeUrl!: Elements.TextElement;
    public menuitems!: Elements.LinkedItemsElement<ContentItem>;
    public address!: Elements.TextElement;
    public email!: Elements.TextElement;
    public mobile!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'menu_logo') {
                    return 'menuLogo';
                }
                if (elementName === 'youtube_url') {
                    return 'youtubeUrl';
                }
                return elementName;
            })
        });
    }
}
