
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu May 29 2025 09:23:39 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Menuitem extends ContentItem {
    public name!: Elements.TextElement;
    public link!: Elements.TextElement;
    public target!: Elements.TextElement;
    public subitems!: Elements.LinkedItemsElement<ContentItem>;
}
