
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Jun 02 2025 10:44:18 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Upcomingeventitem extends ContentItem {
    public name!: Elements.TextElement;
    public date!: Elements.TextElement;
    public venue!: Elements.TextElement;
    public link!: Elements.TextElement;
    public image!: Elements.AssetsElement;
}
